#!/usr/bin/env node
var sass = require('node-sass');
var fs = require('fs');

sass.render({
    includePaths: ['scss/'],
    ouputStyle: 'compressed',
    file: 'scss/screen.scss',
    success: function (data) {
        fs.readFile('css/screen.css', function (err, current) {
            if (data != current) {
                fs.writeFile('css/screen.css', data, function (err) {
                    console.log('%d lines saved.', data.split('\n').length);
                });
            }
            else {
                console.log('No change.');
            }
        });
    },
    error: console.error
});